sudo: false

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.2.0/stack-0.1.2.0-x86_64-linux.gz | gunzip > ~/.local/bin/stack
  - chmod a+x ~/.local/bin/stack
  - chmod +x ./.travis_long

addons:
  apt:
    packages:
    - libgmp-dev

install:
  - ./.travis_long stack --no-terminal --skip-ghc-check setup
  - ./.travis_long stack --no-terminal --skip-ghc-check build
  - ./.travis_long stack --no-terminal --skip-ghc-check test --only-snapshot

script:
  - stack --no-terminal --skip-ghc-check test

cache:
  directories:
  - $HOME/.stack
